#!/bin/sh
############################################
# ant bootstrap
############################################

DIRNAME=`dirname $0`

# OS specific support (must be 'true' or 'false').
cygwin=false;
case "`uname`" in
    CYGWIN*)
        cygwin=true
        ;;
esac

if $cygwin 
then
   java -cp "${JAVA_HOME}\lib\tools.jar;lib\ant-launcher.jar;lib\ant-nodeps.jar;lib\ant.jar" -Dant.home=lib org.apache.tools.ant.launch.Launcher ${*}
else
   java -cp "${JAVA_HOME}/lib/tools.jar:${DIRNAME}/lib/ant-launcher.jar:${DIRNAME}/lib/ant-nodeps.jar:${DIRNAME}/lib/ant.jar" -Dant.home=$DIRNAME/lib org.apache.tools.ant.launch.Launcher ${*}
fi
