DROP TABLE IF EXISTS PUBLIC.SCORE;
DROP TABLE IF EXISTS PUBLIC.ROUND;

CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUND START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_SCORE START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE PUBLIC.ROUND(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ROUND) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUND,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    DATE DATE NOT NULL,
    NOTES CLOB,
    TOTAL_SCORE INTEGER,
    WEATHER VARCHAR(8) NOT NULL,
    TEE_SET_ID BIGINT NOT NULL,
    GOLFER_ID BIGINT NOT NULL
);
CREATE PRIMARY KEY ON PUBLIC.ROUND(ID);

CREATE TABLE PUBLIC.SCORE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_SCORE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_SCORE,
    HOLE INTEGER CHECK ((HOLE >= 1) AND (HOLE <= 18)),
    FAIRWAY BIT NOT NULL,
    GIR BIT,
    PUTTS INTEGER NOT NULL,
    STROKES INTEGER NOT NULL,
    ROUND_ID BIGINT NOT NULL
);
CREATE PRIMARY KEY ON PUBLIC.SCORE(ID);

ALTER TABLE PUBLIC.SCORE ADD CONSTRAINT PUBLIC.FK_SCORE_REF_ROUND FOREIGN KEY(ROUND_ID) REFERENCES PUBLIC.ROUND(ID);
ALTER TABLE PUBLIC.ROUND ADD CONSTRAINT PUBLIC.FK_ROUND_REF_GOLFER FOREIGN KEY(GOLFER_ID) REFERENCES PUBLIC.GOLFER(ID);
ALTER TABLE PUBLIC.ROUND ADD CONSTRAINT PUBLIC.FK_ROUND_REF_TEE_SET FOREIGN KEY(TEE_SET_ID) REFERENCES PUBLIC.TEE_SET(ID);
