package org.open18.model;
// Generated Dec 7, 2007 6:48:49 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * Hole generated by hbm2java
 */
@Entity
@Table(name = "HOLE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NUMBER", "COURSE_ID"}))
public class Hole implements java.io.Serializable {

	private Long id;
	private Course course;
	private int number;
	private int MPar;
	private Integer MHandicap;
	private int LPar;
	private Integer LHandicap;
	private Set<Tee> tees = new HashSet<Tee>(0);

	public Hole() {
	}

	public Hole(Course course, int number, int MPar, int LPar) {
		this.course = course;
		this.number = number;
		this.MPar = MPar;
		this.LPar = LPar;
	}
	public Hole(Course course, int number, int MPar, Integer MHandicap,
			int LPar, Integer LHandicap, Set<Tee> tees) {
		this.course = course;
		this.number = number;
		this.MPar = MPar;
		this.MHandicap = MHandicap;
		this.LPar = LPar;
		this.LHandicap = LHandicap;
		this.tees = tees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURSE_ID", nullable = false)
	@NotNull
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "NUMBER", nullable = false)
	@NotNull
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "M_PAR", nullable = false)
	@NotNull
	public int getMPar() {
		return this.MPar;
	}

	public void setMPar(int MPar) {
		this.MPar = MPar;
	}

	@Column(name = "M_HANDICAP")
	public Integer getMHandicap() {
		return this.MHandicap;
	}

	public void setMHandicap(Integer MHandicap) {
		this.MHandicap = MHandicap;
	}

	@Column(name = "L_PAR", nullable = false)
	@NotNull
	public int getLPar() {
		return this.LPar;
	}

	public void setLPar(int LPar) {
		this.LPar = LPar;
	}

	@Column(name = "L_HANDICAP")
	public Integer getLHandicap() {
		return this.LHandicap;
	}

	public void setLHandicap(Integer LHandicap) {
		this.LHandicap = LHandicap;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "hole")
	public Set<Tee> getTees() {
		return this.tees;
	}

	public void setTees(Set<Tee> tees) {
		this.tees = tees;
	}

}
