package org.open18.model;
// Generated Dec 7, 2007 6:48:49 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TeeSet generated by hbm2java
 */
@Entity
@Table(name = "TEE_SET", uniqueConstraints = {
		@UniqueConstraint(columnNames = {"POS", "COURSE_ID"}),
		@UniqueConstraint(columnNames = {"COLOR", "COURSE_ID"})})
public class TeeSet implements java.io.Serializable {

	private Long id;
	private Course course;
	private String name;
	private String color;
	private Double LCourseRating;
	private Double LSlopeRating;
	private Double MCourseRating;
	private Double MSlopeRating;
	private Integer pos;
	private Set<Tee> tees = new HashSet<Tee>(0);

	public TeeSet() {
	}

	public TeeSet(Course course, String color) {
		this.course = course;
		this.color = color;
	}
	public TeeSet(Course course, String name, String color,
			Double LCourseRating, Double LSlopeRating, Double MCourseRating,
			Double MSlopeRating, Integer pos, Set<Tee> tees) {
		this.course = course;
		this.name = name;
		this.color = color;
		this.LCourseRating = LCourseRating;
		this.LSlopeRating = LSlopeRating;
		this.MCourseRating = MCourseRating;
		this.MSlopeRating = MSlopeRating;
		this.pos = pos;
		this.tees = tees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURSE_ID", nullable = false)
	@NotNull
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "NAME", length = 25)
	@Length(max = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "COLOR", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "L_COURSE_RATING", precision = 17, scale = 0)
	public Double getLCourseRating() {
		return this.LCourseRating;
	}

	public void setLCourseRating(Double LCourseRating) {
		this.LCourseRating = LCourseRating;
	}

	@Column(name = "L_SLOPE_RATING", precision = 17, scale = 0)
	public Double getLSlopeRating() {
		return this.LSlopeRating;
	}

	public void setLSlopeRating(Double LSlopeRating) {
		this.LSlopeRating = LSlopeRating;
	}

	@Column(name = "M_COURSE_RATING", precision = 17, scale = 0)
	public Double getMCourseRating() {
		return this.MCourseRating;
	}

	public void setMCourseRating(Double MCourseRating) {
		this.MCourseRating = MCourseRating;
	}

	@Column(name = "M_SLOPE_RATING", precision = 17, scale = 0)
	public Double getMSlopeRating() {
		return this.MSlopeRating;
	}

	public void setMSlopeRating(Double MSlopeRating) {
		this.MSlopeRating = MSlopeRating;
	}

	@Column(name = "POS")
	public Integer getPos() {
		return this.pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "teeSet")
	public Set<Tee> getTees() {
		return this.tees;
	}

	public void setTees(Set<Tee> tees) {
		this.tees = tees;
	}

}
