/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * County generated by hbm2java
 */
@Entity
@Table(name = "ED_COUNTY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ST_UID", "CNTY_FIPS_CD"}))
public class County extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private State state;
	private String name;
	private String fipsCode;
	private Set<MonitoringLocation> monitoringLocations = new HashSet<MonitoringLocation>(
			0);

	public County() {
	}

	public County(Long uid, State state, String name, String fipsCode) {
		this.uid = uid;
		this.state = state;
		this.name = name;
		this.fipsCode = fipsCode;
	}

	@Id
	@Column(name = "CNTY_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ST_UID", nullable = false)
	@NotNull
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "CNTY_NAME", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CNTY_FIPS_CD", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getFipsCode() {
		return this.fipsCode;
	}

	public void setFipsCode(String fipsCode) {
		this.fipsCode = fipsCode;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "county")
	public Set<MonitoringLocation> getMonitoringLocations() {
		return this.monitoringLocations;
	}

	public void setMonitoringLocations(
			Set<MonitoringLocation> monitoringLocations) {
		this.monitoringLocations = monitoringLocations;
	}

}
