/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FrequencyClassType generated by hbm2java
 */
@Entity
@Table(name = "ED_FREQUENCY_CLASS_TYPE")
public class FrequencyClassType extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private String name;
	private Boolean unitRequired;
	private Boolean boundsRequired;
	private String description;
	private Set<FrequencyClassDescriptor> frequencyClassDescriptors = new HashSet<FrequencyClassDescriptor>(
			0);

	public FrequencyClassType() {
	}

	public FrequencyClassType(Long uid, String name, Boolean unitRequired,
			Boolean boundsRequired) {
		this.uid = uid;
		this.name = name;
		this.unitRequired = unitRequired;
		this.boundsRequired = boundsRequired;
	}

	@Id
	@Column(name = "FCTYP_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "FCTYP_NAME", nullable = false, length = 35)
	@NotNull
	@Length(max = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FCTYP_UNIT_REQUIRED_YN", nullable = false, length = 1)
	@Type(type = "yes_no")
	@NotNull
	public Boolean getUnitRequired() {
		return this.unitRequired;
	}

	public void setUnitRequired(Boolean unitRequired) {
		this.unitRequired = unitRequired;
	}

	@Column(name = "FCTYP_BOUNDS_REQUIRED_YN", nullable = false, length = 1)
	@Type(type = "yes_no")
	@NotNull
	public Boolean getBoundsRequired() {
		return this.boundsRequired;
	}

	public void setBoundsRequired(Boolean boundsRequired) {
		this.boundsRequired = boundsRequired;
	}

	@Column(name = "FCTYP_DESC", length = 300)
	@Length(max = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "frequencyClassType")
	public Set<FrequencyClassDescriptor> getFrequencyClassDescriptors() {
		return this.frequencyClassDescriptors;
	}

	public void setFrequencyClassDescriptors(
			Set<FrequencyClassDescriptor> frequencyClassDescriptors) {
		this.frequencyClassDescriptors = frequencyClassDescriptors;
	}

}
