/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HorizontalCollectionMethod generated by hbm2java
 */
@Entity
@Table(name = "ED_HRZNTL_COLLECTION_METHOD")
public class HorizontalCollectionMethod extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private String name;
	private String description;
	private Set<MonitoringLocation> monitoringLocations = new HashSet<MonitoringLocation>(
			0);
	private Set<Activity> activities = new HashSet<Activity>(0);

	public HorizontalCollectionMethod() {
	}

	public HorizontalCollectionMethod(Long uid, String name) {
		this.uid = uid;
		this.name = name;
	}

	@Id
	@Column(name = "HCMTH_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "HCMTH_NAME", nullable = false, length = 70)
	@NotNull
	@Length(max = 70)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "HCMTH_DESC", length = 150)
	@Length(max = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horizontalCollectionMethod")
	public Set<MonitoringLocation> getMonitoringLocations() {
		return this.monitoringLocations;
	}

	public void setMonitoringLocations(
			Set<MonitoringLocation> monitoringLocations) {
		this.monitoringLocations = monitoringLocations;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horizontalCollectionMethod")
	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

}
