/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Lifestyle generated by hbm2java
 */
@Entity
@Table(name = "ED_LIFESTYLE")
public class Lifestyle extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private Citation citation;
	private String name;
	private String description;
	private Set<Result> results = new HashSet<Result>(0);

	public Lifestyle() {
	}

	public Lifestyle(Long uid) {
		this.uid = uid;
	}

	@Id
	@Column(name = "LIFSTYL_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@GeneratedValue(generator = "LifestyleSequence")
	@SequenceGenerator(name = "LifestyleSequence", sequenceName = "LIFSTYL_SEQ", allocationSize = 1)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITATN_UID")
	public Citation getCitation() {
		return this.citation;
	}

	public void setCitation(Citation citation) {
		this.citation = citation;
	}

	@Column(name = "LIFSTYL_NAME", length = 100)
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LIFSTYL_DESC", length = 300)
	@Length(max = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "lifestyle")
	public Set<Result> getResults() {
		return this.results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

}
