/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * NetType generated by hbm2java
 */
@Entity
@Table(name = "ED_NET_TYPE")
public class NetType extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private SamplingCollectionEquipmentType samplingCollectionEquipmentType;
	private String name;
	private String description;
	private Set<Activity> activities = new HashSet<Activity>(0);

	public NetType() {
	}

	public NetType(Long uid,
			SamplingCollectionEquipmentType samplingCollectionEquipmentType,
			String name) {
		this.uid = uid;
		this.samplingCollectionEquipmentType = samplingCollectionEquipmentType;
		this.name = name;
	}

	@Id
	@Column(name = "NETTYP_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCETYP_UID", nullable = false)
	@NotNull
	public SamplingCollectionEquipmentType getSamplingCollectionEquipmentType() {
		return this.samplingCollectionEquipmentType;
	}

	public void setSamplingCollectionEquipmentType(
			SamplingCollectionEquipmentType samplingCollectionEquipmentType) {
		this.samplingCollectionEquipmentType = samplingCollectionEquipmentType;
	}

	@Column(name = "NETTYP_NAME", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NETTYP_DESC", length = 300)
	@Length(max = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "netType")
	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

}
