/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResultMeasurementQualifier generated by hbm2java
 */
@Entity
@Table(name = "ED_RESULT_MEASURE_QUALIFIER")
public class ResultMeasurementQualifier extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private String code;
	private String description;
	private Set<Result> results = new HashSet<Result>(0);

	public ResultMeasurementQualifier() {
	}

	public ResultMeasurementQualifier(Long uid, String code) {
		this.uid = uid;
		this.code = code;
	}

	@Id
	@Column(name = "RMQLF_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "RMQLF_CD", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "RMQLF_DESC", length = 300)
	@Length(max = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "measurementQualifier")
	public Set<Result> getResults() {
		return this.results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

}
