/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SamplingCollectionEquipmentType generated by hbm2java
 */
@Entity
@Table(name = "ED_SAMPLE_COLLECT_EQUIP_TYPE")
public class SamplingCollectionEquipmentType
		extends
			AttributableUpdateRetireEntity implements java.io.Serializable {

	private Long uid;
	private String name;
	private String description;
	private Set<NetType> netTypes = new HashSet<NetType>(0);
	private Set<SamplingCollectionEquipment> samplingCollectionEquipments = new HashSet<SamplingCollectionEquipment>(
			0);

	public SamplingCollectionEquipmentType() {
	}

	public SamplingCollectionEquipmentType(Long uid, String name) {
		this.uid = uid;
		this.name = name;
	}

	@Id
	@Column(name = "SCETYP_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "SCETYP_NAME", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SCETYP_DESC", length = 300)
	@Length(max = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "samplingCollectionEquipmentType")
	public Set<NetType> getNetTypes() {
		return this.netTypes;
	}

	public void setNetTypes(Set<NetType> netTypes) {
		this.netTypes = netTypes;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "type")
	public Set<SamplingCollectionEquipment> getSamplingCollectionEquipments() {
		return this.samplingCollectionEquipments;
	}

	public void setSamplingCollectionEquipments(
			Set<SamplingCollectionEquipment> samplingCollectionEquipments) {
		this.samplingCollectionEquipments = samplingCollectionEquipments;
	}

}
