/*
 * EDAS2 - TetraTech, Inc.
 *
 * Distributable under GPL license.
 * See terms of license at gnu.org.
 */
package com.tetratech.edas2.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TimeZone generated by hbm2java
 */
@Entity
@Table(name = "ED_TIME_ZONE")
public class TimeZone extends AttributableUpdateRetireEntity
		implements
			java.io.Serializable {

	private Long uid;
	private String code;
	private String name;
	private Long offset;
	private Boolean description;

	public TimeZone() {
	}

	public TimeZone(Long uid, String code, String name, Long offset) {
		this.uid = uid;
		this.code = code;
		this.name = name;
		this.offset = offset;
	}

	@Id
	@Column(name = "TMZONE_UID", unique = true, nullable = false, precision = 6, scale = 0)
	@NotNull
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "TMZONE_CD", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "TMZONE_NAME", nullable = false, length = 80)
	@NotNull
	@Length(max = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TMZONE_OFFSET", nullable = false, precision = 4)
	@NotNull
	public Long getOffset() {
		return this.offset;
	}

	public void setOffset(Long offset) {
		this.offset = offset;
	}

	@Column(name = "TMZONE_DESC", length = 1)
	@Type(type = "yes_no")
	public Boolean getDescription() {
		return this.description;
	}

	public void setDescription(Boolean description) {
		this.description = description;
	}

}
